<?php

namespace GDI\Repository;

/**
 * InputProductTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputProductTabRepository extends \Doctrine\ORM\EntityRepository
{
}
