<?php

namespace GDI\Repository;

/**
 * MBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Jonathan Antivo
 * @since oct 12, 2015
 */
class MBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
