<?php

namespace GDI\Repository;

/**
 * MGameCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MGameCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
