<?php

namespace GDI\Repository;

/**
 * MGameGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MGameGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
