<?php

namespace GDI\Repository;

/**
 * MJurisdictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MJurisdictionRepository extends \Doctrine\ORM\EntityRepository
{
}
