<?php

namespace GDI\Repository;

/**
 * MLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
