<?php

namespace GDI\Repository;

/**
 * MMarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MMarketRepository extends \Doctrine\ORM\EntityRepository
{
}
