<?php

namespace GDI\Repository;

/**
 * MPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MPageRepository extends \Doctrine\ORM\EntityRepository
{
}
