<?php

namespace GDI\Repository;

/**
 * MPlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MPlatformRepository extends \Doctrine\ORM\EntityRepository
{
}
