<?php

namespace GDI\Repository;

/**
 * MRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
