<?php

namespace GDI\Repository;

/**
 * MStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
