<?php

namespace GDI\Repository;

/**
 * MUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MUserRepository extends \Doctrine\ORM\EntityRepository
{
}
