<?php

namespace GDI\Repository;

/**
 * RMarketJurisdictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RMarketJurisdictionRepository extends \Doctrine\ORM\EntityRepository
{
}
