<?php

namespace GDI\Repository;

/**
 * RUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RUserRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
