<?php

namespace GDI\Repository;

/**
 * TJurisdictionProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TJurisdictionProductRepository extends \Doctrine\ORM\EntityRepository
{
}
