<?php

namespace GDI\Repository;

/**
 * TProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TProductRepository extends \Doctrine\ORM\EntityRepository
{

	public function getInputFilter()
    {
        $inputFilter = new \Zend\InputFilter\InputFilter();
        $factory = new \Zend\InputFilter\Factory();

        $inputFilter->add($factory->createInput(array(
            'name' => 'control_id',
            'validators' => array(
                'name' => '\DoctrineModule\Validator\NoObjectExists',
                'options' => array(
                    'object_repository' => this,
                    'fields' => array('control_id'),
                ),
            ),
        )));

        return $inputFilter;
    }
}
