<?php

namespace GDI\Repository;

/**
 * WJurisdictionProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WJurisdictionProductRepository extends \Doctrine\ORM\EntityRepository
{
}
