<?php

namespace GDI\Repository;

/**
 * WMarketProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WMarketProductRepository extends \Doctrine\ORM\EntityRepository
{
}
