<?php 

$title = "Game Group Input";
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('game-group', array('action' => 'add')));
?>
            
<div class="row">
    <h2><?php  echo $this->escapeHTML($this->translate('Game Group Input')); ?></h2>
    <div class="box box-info">
        <?php
            echo $this->form()->openTag($form) . "\n";
            echo $this->formHidden($form->get('game_group_id')) . "\n";
            echo $this->formHidden($form->get('update_time')) . "\n";
        ?>
            <div class="box-body">
                    <div class="form-group">
                            <?php echo $this->formLabel($form->get('game_group_name')); ?>
                            <div class="col-sm-10">
                            <?php echo $this->formElement($form->get('game_group_name')); ?>
                            <?php echo $this->formElementerrors($form->get('game_group_name')); ?>
                            </div>
                    </div>

            </div>
            <div class="box-footer text-center">
            <?php
                 echo $this->formSubmit($form->get('submit')) . "\n";
                 echo $this->formReset($form->get('reset')) . "\n";
                 echo $this->form()->closeTag();
              ?>
            </div>
        <div class="col-md-6"></div>
    </div>
</div>