<?php 

$title = "Jurisdiction Input";
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('jurisdiction', array('action' => 'edit', 'id' => $this->id)));
?>
            
<div class="row">
    <h2><?php  echo $this->escapeHTML($this->translate('Jurisdiction Input')); ?></h2>
    <div class="box box-info">
        <?php
            echo $this->form()->openTag($form) . "\n";
            echo $this->formHidden($form->get('jurisdiction_id')) . "\n";
            echo $this->formHidden($form->get('update_time')) . "\n";
        ?>
        <div class="box-body">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('jurisdiction_name')); ?>
                <div class="col-sm-10">
                    <?php echo $this->formElement($form->get('jurisdiction_name')); ?>
                    <?php echo $this->formElementerrors($form->get('jurisdiction_name')); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('jurisdiction_abbr')); ?>
                <div class="col-sm-10">
                    <?php echo $this->formElement($form->get('jurisdiction_abbr')); ?>
                    <?php echo $this->formElementerrors($form->get('jurisdiction_abbr')); ?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('is_regulator')); ?>
                <div class="col-sm-10">
                    <?php echo $this->formElement($form->get('is_regulator')); ?>
                </div>
            </div>
        </div>
        <div class="box-footer text-center">
        <?php
             echo $this->formSubmit($form->get('submit')) . "\n";
             echo $this->formReset($form->get('reset')) . "\n";
             echo $this->form()->closeTag();
          ?>
        </div>
        <div class="col-md-6"></div>
    </div>
</div>