<?php 

$title = "Platform Input";
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('platform', array('action' => 'edit', 'id' => $this->id)));
?>
            
<div class="row">
    <h2><?php  echo $this->escapeHTML($this->translate('Platform Input')); ?></h2>
    <div class="box box-info">
        <?php
            echo $this->form()->openTag($form) . "\n";
            echo $this->formHidden($form->get('platform_id')) . "\n";
            echo $this->formHidden($form->get('update_time')) . "\n";
        ?>
        <div class="box-body">
                <div class="form-group">
                        <?php echo $this->formLabel($form->get('platform_name')); ?>
                        <div class="col-sm-10">
                        <?php echo $this->formElement($form->get('platform_name')); ?>
                        <?php echo $this->formElementerrors($form->get('platform_name')); ?>
                        </div>
                </div>

        </div>
        <div class="box-footer text-center">
        <?php
             echo $this->formSubmit($form->get('submit')) . "\n";
             echo $this->formReset($form->get('reset')) . "\n";
             echo $this->form()->closeTag();
          ?>
        </div>
        <div class="col-md-6"></div>
    </div>
</div>