<?php
$title = 'Please login first';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('auth'));
$form->prepare();
?>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="login-form" style="width: 95%; margin:27% auto">
			<div class="box box-info">
				<div class="box-header text-center">
					<div>
						<img src="/img/logo.png" width="250" height="25">
					</div>
					<h2 class="page-header">Game Detail Information</h2>
				</div>
				<!-- /.box-header -->
				<!-- form start -->
				     <?php
                       echo $this->form()->openTag($form);
                      ?>
					<div class="box-body">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-2 control-label">User ID</label>
							<div class="col-sm-10">
								  <?php echo $this->formElement($form->get('username')); ?>
                                  <?php echo $this->formElementerrors($form->get('username')); ?>
							</div>
						</div>
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
							<div class="col-sm-10">
								 <?php echo $this->formElement($form->get('password')); ?>
                                 <?php echo $this->formElementerrors($form->get('password')); ?>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<div class="checkbox">
									<label> <input type="checkbox">Remember me
									</label>
								</div>
							</div>
						</div>
					</div>
					<p class="text-center">
					<?php echo $this->render('flashmessenger/layout')?></p>
					<!-- /.box-body -->
					<div class="box-footer">
						<button type="reset" class="btn btn-default">Cancel</button>
						<?php echo $this->formSubmit($form->get('Loginsubmit')); ?>
					</div>

					<div class="pull-right hidden-xs">
						<p></p>
						<a href="<?php echo $this->url('auth',array('action'=>'forgot-password'))?>"><b>Password re-issue ?</b></a>
					</div>
					<!-- /.box-footer -->
				<?php echo $this->form()->closeTag();?>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>