<?php
$title = 'Please login first';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('auth',array('action'=>'logout')));
$form->prepare();
?>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="login-form" style="width: 95%; margin:27% auto">
			<div class="box box-info">
				<div class="box-header text-center">
					<div>
						<img src="/img/logo.png" width="250" height="25">
					</div>
					<h2 class="page-header">Game Detail Information</h2>
				</div>
				<!-- /.box-header -->
				<!-- form start -->
				    <?php
                       echo $this->form()->openTag($form);
                      ?>
					<div class="box-body">
						<div class="form-group">
						     <p class="text-center"> <small>Please Confirm logout by clicking YES button</small> </p>
						</div>
					</div>
						<p class="text-center">
					<?php echo $this->render('flashmessenger/layout')?></p>
					<!-- /.box-body -->
					<div class="box-footer">
					    <button type="submit" class="btn btn-default">Cancel</button>
						<?php echo $this->formSubmit($form->get('LogoutYes')); ?>
						
					</div>

					<!-- /.box-footer -->
				<?php echo $this->form()->closeTag();?>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>