<div class="container">
        <div class="box">
            <span class="glyphicon glyphicon-arrow-down" style="margin-left: 50%;font-size: 50px;">
        </div>
    </div>
    
    <!-- second container -->
    <div class="row">
        <!-- 1st column -->
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>Control No</dt>
                <dd>Vestibulum id ligula porta felis euismod semper eget lacinia odio</dd>
              
                <dt>Title</dt>
                <dd>Donec id elit non mi por</dd>
              
                <dt>Developed In</dt>
                <dd>tiam porta sem malesuada m</dd>

                <dt>Category</dt>
                <dd>tiam porta sem malesuada m</dd>

                <dt>Type</dt>
                <dd> malesuada m</dd>

                <dt>Overview</dt>
                <dd> malesuada m</dd>

                <dt>Development Start (Est)</dt>
                <dd> malesuada m</dd>

                <dt>Development Finish (Est)</dt>
                <dd></dd>

                <dt>Development Finish (Est)</dt>
                <dd></dd>

            </dl>



        </div><!-- end of 1st column -->


        <!-- 2nd column -->
        <div class="col-md-6">

            <dl class="dl-horizontal">
                <dt>Game Version No.</dt>
                <dd>Vestibulum id ligula porta felis euismod semper eget lacinia odio</dd>
                  
                <dt>Platform</dt>
                <dd>Donec id elit non mi por</dd>
                  
                <dt>Market</dt>
                <dd>tiam porta sem malesuada m</dd>

                <dt>Group</dt>
                <dd></dd>

                <dt>Target</dt>
                <dd></dd>

                <dt>Characteristics</dt>
                <dd></dd>

                <dt>Development Start (Rs)</dt>
                <dd></dd>

                <dt>Development Finish (Rs)</dt>
                <dd></dd>

            </dl>


        </div><!-- end of 2nd column -->

    </div><!-- end of row -->
    <div class="container">
        <div class="row">  
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">CA</div>

                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col-sm-5">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Est)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Est)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Est)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Est)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>
                        
                            <div class="col-sm-7">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Rs)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Rs)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Rs)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Rs)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>

                        </div>

                        

                    </div>
                </div> <!-- end of CA -->

                <div class="panel panel-default">
                    <div class="panel-heading">MO</div>

                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col-sm-5">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Est)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Est)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Est)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Est)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>
                        
                            <div class="col-sm-7">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Rs)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Rs)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Rs)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Rs)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>

                        </div>

                        

                    </div>
                </div>
            </div> <!-- End of MO -->

            
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">NV</div>

                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col-sm-5">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Est)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Est)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Est)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Est)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>
                        
                            <div class="col-sm-7">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Rs)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Rs)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Rs)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Rs)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>

                        </div>

                        

                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">SABS</div>

                    <div class="panel-body">
                        
                        <div class="row">
                            <div class="col-sm-5">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Est)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Est)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Est)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Est)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>
                        
                            <div class="col-sm-7">
                                <dl class="dl-horizontal">
                                    <dt>Submission(Rs)</dt>
                                    <dd class="dd120">1234567</dd>
                                      
                                    <dt>Approval(Rs)</dt>
                                    <dd class="dd120"></dd>
                                      
                                    <dt>MasterRelese(Rs)</dt>
                                    <dd class="dd120"></dd>

                                    <dt>Launch(Rs)</dt>
                                    <dd class="dd120"></dd>
                                </dl>
                            </div>

                        </div>

                        

                    </div>
                </div>
            </div> <!-- End of SABS -->                       



        </div><!-- end of row -->
    </div><!-- end of container -->
