<?php $paging = $this->paginationHelper($marketproductList, $page, '/product-information', 10); ?>

<table class="table table-hover table-condensed">
	<tbody>
		<tr>
			<th>Request</th>
			<th>Title</th>
			<th>Platform</th>
			<th>Category</th>
			<th>Market</th>
			<th>Status</th>
			<th>Submission</th>
			<th>Approval</th>
			<th>Approval Status</th>
			<th>Master Release</th>
			<th>Master Release Status</th>
			<th>Sales Promotion Status</th>
			<th>Lauching</th>
		</tr>
		<?php foreach ($marketproductList as $list): ?>
				<?php $url = $this->url('approved-publication', array('id' => $list->getMarketProductId()), true) ?>
				<?php $detailUrl = $this->url('product-information', array('action' => 'detail', 'id' => $list->getMarketProductId()), true) ?>
				<?php $inputtab = $getEntityManager->getRepository('GDI\Entity\InputProductTab')->findOneBy(array('market_product_id' => $list->getMarketProductId() )); ?>
				<?php $editUrl = $inputtab ? "/input-product-information/{$inputtab->getId()}?controlno={$inputtab->getControlNo()}&tabno={$inputtab->getTabNo()}" : ''; ?>
			<tr>
				<td>
					<a href="<?php echo $editUrl ?>" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  
					<a href="<?php echo $url ?>" title="view details"><i class="fa fa-fw fa-external-link"></i></a>
				</td>

				<td> <a href="<?php echo $detailUrl ?>"> <span class="label bg-aqua"><?php echo $list->getTitle() ?> <?php echo $list->getMarketProductId() ?> </span> </a></td>
				<td><?php echo $list->getPlatform()->getPlatformName() ?></td>
				<td><?php echo $list->getGameCategory()->getGameCategoryName() ?></td>
				<td><?php echo $list->getMarket()->getMarketName() ?></td>
				<td> 
					<?php if (!is_null($jp = $list->getOneJurisProductByCriterion()) ): ?>
						<?php echo $jp->getStatus()->getStatusName() ?>	
					<?php endif; ?>
				</td>
				<td>
					<?php $submission = $list->getSubmission(); ?>	
					<span class="label <?php echo $submission['class'] ?>">
					<?php echo $submission['date']; ?>
					</span>
				</td>

				<td>
					<?php $approval = $list->getApproval(); ?>	
					<span class="label <?php echo $approval['class'] ?>">
					<?php echo $approval['date']; ?>
					</span>
				</td>
				<td> 
					<?php foreach($list->getApprovalStatus() as $key => $each): ?>
						<span class="glyphicon glyphicon-<?php echo $each ? 'check' : 'unchecked' ?>" aria-hidden="true"></span>
						<?php echo $key; ?> 
					<?php endforeach; ?>
				
				</td>
				<td>
					<?php $release = $list->getRelease(); ?>	
					<span class="label <?php echo $release['class'] ?>">
					<?php echo $release['date']; ?>
					</span>
				</td>
				<td> 
					<?php foreach($list->getMasterReleaseStatus() as $key => $each): ?>
						<span class="glyphicon glyphicon-<?php echo $each ? 'check' : 'unchecked' ?>" aria-hidden="true"></span>
						<?php echo $key; ?> 
					<?php endforeach; ?>
				</td>
				<td>
					<span class="sp-status">
						<?php if ($list->getProduct()->getRGslickDate()): ?>
							<i class="fa fa-circle-thin"></i>
						<?php endif; ?>
						<?php if ($list->getProduct()->getRArtworkSpDate()): ?>
							<i class="fa  fa-star-o"></i>
						<?php endif; ?>
						<?php if ($list->getProduct()->getRDemoDate()): ?>
							<i class="fa fa-moon-o"></i>
						<?php endif; ?>
						<?php if ($list->getProduct()->getRMovieDate()): ?>
							<i class="fa  fa-film"></i>
						<?php endif; ?>
						<?php if ($list->getProduct()->getRWebsiteDate()): ?>
							<i class="fa fa-heart-o"></i>
						<?php endif; ?>
					</span>
				</td>

				<td>
					<?php $launch = $list->getLaunch(); ?>	
					<span class="label <?php echo $launch['class'] ?>">
					<?php echo $launch['date']; ?>
					</span>
				</td>
			</tr>

		<?php endforeach; ?>
	</tbody>
</table>

<div class="paging">
    
</div>

<?php echo $paging; ?>