<?php
	$product = $marketProduct->getProduct();
	$jurisdictionProduct = $marketProduct->getTJurisdictionProductMarketProduct();
?>

<div class="container">
	<h1>Detailed Product Information</h1>
				<div class="col-lg-5">
					<img src="<?php echo $this->basePath() ?> /img/uploads/<?php echo $product->getGameImagePass() ?>" alt="" class="img-responsive center-block"/>
				</div>
				<div class="col-lg-7 product-info">
					<div class="row">
						<div class="col-md-4 game-version">
							<h3>Game Version No. </h3>
						</div>
						<form class="form-horizontal col-md-4">
							<div class="form-group">
								<select class="form-control" id="gvn_select">
									<?php foreach($getOptionGvn as $key => $each): ?>
										<option value="<?php echo $key ?>" <?php echo $marketProduct->getGvn() == $each ? 'selected' : '' ?>><?php echo $each ?></option>
									<?php endforeach; ?>
								</select>
							</div>
								
						</form>
						<div class="col-md-4"></div>
					</div>
					<h3>Game Information</h3>
					<div id="game-info">
						<div class="row">
							<div class="col-md-2 ">Title</div>
							<div class="col-md-10"><?php echo $marketProduct->getTitle() ?></div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Platform</div>
							<div class="col-md-4"> <?php echo $marketProduct->getPlatform()->getPlatformName() ?> </div>
							<div class="col-md-2 ">Category</div>
							<div class="col-md-4"><?php echo $marketProduct->getGameCategory()->getGameCategoryName() ?></div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Group</div>
							<div class="col-md-4"> <?php echo $marketProduct->getGameGroup()->getGameGroupName() ?> </div>
							<div class="col-md-2 ">Developed in</div>
							<div class="col-md-4"><?php echo $marketProduct->getBranch()->getBranchName() ?></div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Type</div>
							<div class="col-md-4"> <?php echo $marketProduct->getType() ?> </div>
							<div class="col-md-2 ">Target</div>
							<div class="col-md-4"> <?php echo $marketProduct->getTarget() ?> </div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Overview</div>
							<div class="col-md-10"> <?php echo $marketProduct->getOverview() ?> </div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Characteristics</div>
							<div class="col-md-10"> <?php echo $marketProduct->getCharacteristics() ?> </div>
						</div>
						<div class="row">
							<div class="col-md-2 ">Remarks</div>
							<div class="col-md-10"><?php echo $marketProduct->getRemarks() ?></div>
						</div>
					</div>
					<h3>Approval Status</h3>
					<div id="approval-status">
						<div class="row">
							<div class="col-md-2"></div>
								<?php foreach($avail_abbrs as $abbr): ?>
									<div class="col-md-2 <?php echo $abbr == $criterion ? 'bg-aqua':'' ?>"><?php echo $abbr ?></div>
								<?php endforeach; ?>
							<div class="col-md-2"></div>
						</div>
						<?php foreach ($approvalStatus as $key => $approval): ?>
							<div class="row">
								<div class="col-md-2"><?php echo $key ?></div>
								<?php foreach ($approval as $a): ?>
									<div class="col-md-2"> <span class="label <?php echo $a['class'] ?>"> <?php echo $a['date'] ?> </span> </div>
								<?php endforeach; ?>
							</div>
						<?php endforeach; ?>
						
						<h3>Sale Promotion Status</h3>
						<div id="sales-status">
							<div class="row">
								<div class="col-md-2 ">Artwork(Sales Promotion)</div>
								<div class="col-md-4"><?php echo $product->getEArtworkSpDate('m/d/Y') ?></div>
								<div class="col-md-2 ">Movie</div>
								<div class="col-md-4"><?php echo $product->getRMovieDate('m/d/Y') ?></div>
							</div>
							<div class="row">
								<div class="col-md-2 ">G-Slick</div>
								<div class="col-md-4"><?php echo $product->getEGslickDate('m/d/Y') ?></div>
								<div class="col-md-2 ">Artwork(Training)</div>
								<div class="col-md-4"> <?php echo $product->getEArtworkTrDate('m/d/Y') ?></div>
							</div>
							<div class="row">
								<div class="col-md-2 ">Demo Software</div>
								<div class="col-md-4"><?php echo $product->getEDemoDate('m/d/Y') ?></div>
								<div class="col-md-2 ">Website</div>
								<div class="col-md-4"><?php echo $product->getEWebsiteDate('m/d/Y') ?></div>
							</div>
							<div class="row">
								<div class="col-md-2 ">Return Demo Software</div>
								<div class="col-md-4"><?php echo $product->getIsReturnDemo() == 0 ? 'No' : 'Yes' ?></div>
								<div class="col-md-2"></div>
								<div class="col-md-4"></div>
							</div>
						</div>
					</div>
				</div>
			</div>

<script type="text/javascript">

$(function(){
	'use strict'
	$('#gvn_select').on('change',function(){
		window.location.href = "/product-information/detail/" + $(this).val();
	});
});
</script>