	<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet('//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css');
 ?>
<!-- script -->  
<?php
 $this->headScript()
 		->appendFile ('//cdn.jsdelivr.net/momentjs/latest/moment.min.js')
       	->appendFile ('//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js')
       ;
 ?>
 <?php $params = $this->params()->fromQuery(); ?>
 
<div class="container">
				<div class="row">
					<h1>Product Information</h1>
					<div class="box box-info">
						<div class="box-header">
							<h2 class="box-title">Search</h2>
							<div class="box-tools pull-right">
								<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
								</button>
								<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
							</div>
						</div>
						<div class="box-body pad">
							<form>
								<div class="row col-md-12">
									<div class="form-group col-md-4">
										<label for="title" class="col-md-2">Title</label> 
										<input type="text" class="form-control col-md-10" id="title" name="title" placeholder="Name" value="">
									</div>
									<div class="form-group col-md-4">
										<label for="exampleInputEmail2">Platform</label> <select name="platform"
											class="form-control">
											<option value="">Select All</option>
											<?php foreach($platform as $each): ?>
												<option value ="<?php echo $each->getPlatformId() ?>"> <?php echo $each->getPlatformName() ?> </option>
											<?php endforeach; ?>
										</select>
									</div>
									<div class="form-group col-md-4">
										<label for="exampleInputEmail2">Category</label> <select name="category"
											class="form-control" id="sel1">
											<option value="">Select All</option>
											<?php foreach($category as $each): ?>
												<option value ="<?php echo $each->getGameCategoryId() ?>"> <?php echo $each->getGameCategoryName() ?> </option>
											<?php endforeach; ?>
										</select>
									</div>
								</div>
								<div class="row col-md-12">
									<div class="form-group col-md-3">
										<label for="exampleInputName2">Market</label> <select name="market"
											class="form-control" id="sel1">
											<option value="">Select All</option>
											<?php foreach($market as $each): ?>
												<option value ="<?php echo $each->getMarketId() ?>"> <?php echo $each->getMarketName() ?> </option>
											<?php endforeach; ?>
										</select>
									</div>
									<div class="form-group col-md-3">
										<label for="exampleInputEmail2">Status</label> <select name="status"
											class="form-control" id="sel1">
											<option value="">Select All</option>
											<?php foreach($status as $each): ?>
												<option value ="<?php echo $each->getStatusId() ?>"> <?php echo $each->getStatusName() ?> </option>
											<?php endforeach; ?>
										</select>
									</div>
									<div class="col-md-6"></div>
								</div>
								<div class="row col-md-12">
									<div class="form-group col-md-6">
										<label for="submission">Submission</label> 
										<input type="checkbox" name="eSubmissionDate" aria-label="...">Estimated 
										<input type="checkbox" name="rSubmissionDate" aria-label="...">Done 
										<div class="input-group col-md-12">
											<div class="input-group-addon">
												<i class="fa fa-calendar"></i>
											</div>
											<input type="text" class="form-control daterange" name="submissionDate" >
										</div>
									</div>
									
									<div class="form-group col-md-6">
										<label for="approval">Approval</label>
										<input type="checkbox" name="eApprovalDate" aria-label="...">Estimated 
										<input type="checkbox" name="rApprovalDate" aria-label="...">Done 
										<div class="input-group col-md-12">
											<div class="input-group-addon">
												<i class="fa fa-calendar"></i>
											</div>
											<input type="text" name="approvalDate" class="form-control daterange">
										</div>
									</div>
								</div>
								<div class="row col-md-12">
									<div class="form-group col-md-6">
										<label for="submission">Master Release</label> 
										<input type="checkbox" name="eReleaseDate" aria-label="...">Estimated 
										<input type="checkbox" name="rReleaseDate" aria-label="...">Done 
										<div class="input-group col-md-12">
											<div class="input-group-addon">
												<i class="fa fa-calendar"></i>
											</div>
											<input type="text" class="form-control daterange" name="releaseDate">
										</div>
									</div>
									<div class="form-group col-md-6">
										<label for="approval">Launch</label>
										<input type="checkbox" name="eLaunchDate" aria-label="...">Estimated 
										<input type="checkbox" name="rLaunchDate" aria-label="...">Done 
										<div class="input-group col-md-12">
											<div class="input-group-addon">
												<i class="fa fa-calendar"></i>
											</div>
											<input type="text" class="form-control daterange" name="launchDate">
										</div>
									</div>
								</div>
								<button class="btn btn-primary text-right list-button">Submit</button>
							</form>
						</div>
					</div>
				</div>
			<br/>
			<div class="row">
				<div class="box box-info">
					<div class="box-header">
						<h1 class="box-title"><span class="fa fa-gear"></span> Product Information </h1>
							<small> (list)  * Estimated: 
							<span class="text-yellow" title="yellow"><i class="fa fa-fw fa-square"></i></span> 
							Done: <span class="text-orange" title="orange"><i class="fa fa-fw fa-square"></i></span>
							<br/>
							</small>
						<br/>
						<p>	<i class="fa fa-star-o"></i> = Artwork (Sales Promotion),
							<i class="fa fa-circle-thin"></i> = GSlick,
							<i class="fa fa-moon-o"></i> = Demo Software,
							<i class="fa  fa-film"></i> = Movie,
							<i class="fa  fa-square-o"></i> = Artwork (Training),
							<i class="fa fa-heart-o"></i> = Website,
						</p>
						<div class="box-tools">
							<div class="input-group input-group-sm" style="width:180px;">
								<input type="text" name="table_search" class="form-control pull-right" placeholder="Control No">
								<div class="input-group-btn">
									<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button> 
									<button type="button" class="btn btn-box-tool hidden-xs" data-widget="collapse">
									<i class="fa fa-minus"></i>
									</button>
									<button type="button" class="btn btn-box-tool hidden-xs" data-widget="remove"><i class="fa fa-times"></i></button>
								</div>
							</div>
						</div>
					</div>
					<div class="box-body table-responsive no-padding">
						<?php echo $this->partial('_list.phtml', array(
							'marketproductList' => $marketproductList ,
							'page' => $page ,
							'getEntityManager' => $getEntityManager
						 )); ?>

					</div>
				</div>
			</div>	<!--container-->



		<script type="text/javascript">
			$(function() {
			    $('.daterange').daterangepicker({
			    	locale: { cancelLabel: 'Clear' }  
			    });

			    $('.daterange').on('cancel.daterangepicker', function(ev, picker) {
			    	$(this).val('');
				});


				$('.daterange').val('');
			});
		</script>