<?php
$flash = $this->flashMessenger();
 $flash->setMessageOpenFormat('<div%s>
     <a type="button" class="close" data-dismiss="alert" aria-hidden="true" href="#" style="text-decoration:none;float:right">
         &times;
     </a>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

 echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
 echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
 echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
 echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));