<?php

namespace Application\Repository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLanguage()
    {
        $querybuilder = $this->createQueryBuilder('l');
        return $querybuilder->select('l')
                    //->groupBy('l.continent')
                    ->orderBy('l.id', 'ASC')
                    ->getQuery()->getResult();
    }
}
