<nav style="display:block">
	<ul class="nav nav-pills container" role="tablist">
	<?php foreach ($this->container as $page): ?>
		<li role="presentation" class="<?php echo $page->isActive() ? "active":""?>"> <!-- updated this when all pages are created // -->
		
		<a href="<?php echo  $page->getHref()?>" title="<?php echo $page->getLabel()?>" id="<?php echo $page->getId()?>">
			<i class="fa <?php  echo $page->get('class') ?>"></i>
			<br /><?php echo $page->getLabel()?>
		    </a>
		</li>
   <?php endforeach;?>
	</ul>
</nav>
<section>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6"> <?php echo $this->render('flashmessenger/layout')?> </div>
    <div class="col-md-3"></div>
</div>
</section>